### ISSUE TITLE
Backward ace-jump-zap-to-char behaves differently than zap-to-char

### ISSUE THREAD

**Issue by sherrman** [waymondo/ace-jump-zap#10]
Both examples start with a buffer like (where the cursor is on the character above the caret):

```
a_b_a
  ^
```

Ex 1: zap-to-char going backwards inclusively kills the character.

```
C-u -1 M-x zap-to-char a
b_a
^
```

Ex 2: ace-jump-zap-to-char does not.

```
C-u -1 M-x ace-jump-zap-to-char a
(selecting the first "a")
ab_a
 ^
```

The forward examples work consistently with their non-ace-jump counterpart.  The `*-dwim` functions also behave similarly. 

Is this intentional? Thanks!

**Comment by waymondo** [comment]
Yes, you are definitely right. Thank you for bringing this to my attention. The behavior of `ace-zump-zap-to-char` and `ace-jump-zap-up-to-char` was actually reversed when mirrored backwards from the point. The last commit should fix this.

**Comment by sherrman** [comment]
Awesome! Thanks!
