### ISSUE TITLE
ace-jump-zap error after upgrading to melpa 20150227.1740

### ISSUE THREAD

**Issue by Jehops** [waymondo/ace-jump-zap#8]
I see `ajz/maybe-sort-candidate-list: Symbol's function definition is void: -sort` in the minibuffer.  I tested this without a init file as well with the same result.

Just let me know if I can test anything or provide more information.

**Comment by waymondo** [comment]
looks you are missing the new `dash.el` dependency. I thought it should have updated automatically but maybe my header `package-requires` header format is incorrect. how did you update? `M-x package-install dash` should fix.

**Comment by Jehops** [comment]
justin talbott <notifications@github.com> writes:

> looks you are missing the new `dash.el` dependency. I thought it should have
> updated automatically but maybe my header `package-requires` header format is
> incorrect. how did you update? `M-x package-install dash` should fix.

Dash did get updated to 20150311.2355 when I did M-x list-packages U.  I
removed and reinstalled dash and ace-jump-*, but no change.

**Comment by Jehops** [comment]
I also noticed that `ace-jump-mode` will work until I used `ace-jump-zap`, then I see the same error as above for `ace-jump-mode` as well.

**Comment by waymondo** [comment]
Seems dash isn't loaded. If you eval `(require 'dash)` it should work. You can put that in your .emacs, but I also added it to `ace-jump-zap` so you won't need to require it elsewhere after your next update from MELPA.

**Comment by Jehops** [comment]
Confirmed.  It's working after updating again from Melpa.  Thanks.
